// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7f3_0XKwa4Mi0y0tr1uhYVimgSlQiIrk',
    appId: '1:800249255403:web:d10ece011787f75cd975ae',
    messagingSenderId: '800249255403',
    projectId: 'restaurante-59c72',
    authDomain: 'restaurante-59c72.firebaseapp.com',
    storageBucket: 'restaurante-59c72.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqraqJEAXMlSL0aNXCKvKp73ooDI43SqU',
    appId: '1:800249255403:android:2b8463221d068972d975ae',
    messagingSenderId: '800249255403',
    projectId: 'restaurante-59c72',
    storageBucket: 'restaurante-59c72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh0-8HL9vFNAqvnhkjEydKREu6zshcpvQ',
    appId: '1:800249255403:ios:9f1eec591ff9319dd975ae',
    messagingSenderId: '800249255403',
    projectId: 'restaurante-59c72',
    storageBucket: 'restaurante-59c72.appspot.com',
    iosBundleId: 'com.example.learningb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh0-8HL9vFNAqvnhkjEydKREu6zshcpvQ',
    appId: '1:800249255403:ios:9f1eec591ff9319dd975ae',
    messagingSenderId: '800249255403',
    projectId: 'restaurante-59c72',
    storageBucket: 'restaurante-59c72.appspot.com',
    iosBundleId: 'com.example.learningb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7f3_0XKwa4Mi0y0tr1uhYVimgSlQiIrk',
    appId: '1:800249255403:web:7a6925c43aca62d4d975ae',
    messagingSenderId: '800249255403',
    projectId: 'restaurante-59c72',
    authDomain: 'restaurante-59c72.firebaseapp.com',
    storageBucket: 'restaurante-59c72.appspot.com',
  );
}
